spring:
  application:
    name: micro-pay

server:
  port: 9000
  servlet:
    context-path: /pay

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.powernode
  consumer:
    timeout: 50000
    retries: 0
    check: false


